apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: deploy-{{.Release.Name}}
  name: deploy-{{.Release.Name}}
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      app: deploy-{{.Release.Name}}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: deploy-{{.Release.Name}}
    spec:
      containers:
      - image: {{ .Values.image }}
        name: warehouseapi
        resources: {}
status: {}
